services:
  - type: web
    name: tender-node
    env: docker
    plan: free
    region: oregon
    rootDir: go-chain
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TENDER_API_PORT
        value: "10000"
      - key: TENDER_P2P_PORT
        value: "3030"
      - key: TENDER_DATA_DIR
        value: /data
      - key: TENDER_CONSENSUS
        value: pos
